/**
 * Generated Gallery Events Manifest
 * ---------------------------------
 * This file is automatically generated by scripts/generate-gallery-manifest.js
 * Scans public/Gallery/Events/<Event Folder>/ and public/Gallery/Press/.
 * 
 * To add an event: Simply create a folder in public/Gallery/Events/<Your Event Name>/
 * with images (01.jpg, 02.jpg, ...).
 * To customize metadata: Edit public/Gallery/Events/events.json.
 */

export interface GalleryEvent {
    id: string;
    slug?: string;
    name: string;
    title?: string;
    folder: string;
    category?: string;
    date?: string;
    description?: string;
    location?: string;
    thumbnail?: string;
    images: string[];
}

export const pressImages: string[] = [
    "/Gallery/Press/01.jpg",
    "/Gallery/Press/02.jpg",
    "/Gallery/Press/03.jpeg",
    "/Gallery/Press/03.jpg",
    "/Gallery/Press/04.jpg",
    "/Gallery/Press/05.jpg",
    "/Gallery/Press/06.jpg",
    "/Gallery/Press/07.jpg",
    "/Gallery/Press/08.jpg"
];

export const galleryEvents: GalleryEvent[] = [
    {
        "id": "cathlab-inauguration",
        "slug": "cathlab-inauguration",
        "name": "Cathlab Inauguration",
        "title": "Cathlab Inauguration",
        "folder": "/Gallery/Events/Cathlab Inauguration",
        "category": "Hospital Events",
        "date": "",
        "description": "",
        "location": "SilverLine Hospital Trichy",
        "thumbnail": "/Gallery/Events/Cathlab%20Inauguration/1.jpg",
        "images": [
            "/Gallery/Events/Cathlab%20Inauguration/1.jpg",
            "/Gallery/Events/Cathlab%20Inauguration/2.jpg",
            "/Gallery/Events/Cathlab%20Inauguration/3.jpg",
            "/Gallery/Events/Cathlab%20Inauguration/4.jpg",
            "/Gallery/Events/Cathlab%20Inauguration/5.jpg",
            "/Gallery/Events/Cathlab%20Inauguration/6.jpg",
            "/Gallery/Events/Cathlab%20Inauguration/7.jpg",
            "/Gallery/Events/Cathlab%20Inauguration/8.jpg",
            "/Gallery/Events/Cathlab%20Inauguration/9.jpg",
            "/Gallery/Events/Cathlab%20Inauguration/10.jpg",
            "/Gallery/Events/Cathlab%20Inauguration/11.jpg",
            "/Gallery/Events/Cathlab%20Inauguration/12.jpg",
            "/Gallery/Events/Cathlab%20Inauguration/13.jpg"
        ]
    },
    {
        "id": "dental",
        "slug": "dental",
        "name": "Dental",
        "title": "Dental",
        "folder": "/Gallery/Events/Dental",
        "category": "Hospital Events",
        "date": "",
        "description": "",
        "location": "SilverLine Hospital Trichy",
        "thumbnail": "/Gallery/Events/Dental/1.jpg",
        "images": [
            "/Gallery/Events/Dental/1.jpg",
            "/Gallery/Events/Dental/2.jpg",
            "/Gallery/Events/Dental/3.jpg",
            "/Gallery/Events/Dental/4.jpg",
            "/Gallery/Events/Dental/5.jpg",
            "/Gallery/Events/Dental/6.jpg",
            "/Gallery/Events/Dental/7.jpg",
            "/Gallery/Events/Dental/8.jpg",
            "/Gallery/Events/Dental/9.jpg",
            "/Gallery/Events/Dental/10.jpg",
            "/Gallery/Events/Dental/11.jpg"
        ]
    },
    {
        "id": "hospital-inogration",
        "slug": "hospital-inogration",
        "name": "Hospital Inogration",
        "title": "Hospital Inogration",
        "folder": "/Gallery/Events/Hospital Inogration",
        "category": "Hospital Events",
        "date": "",
        "description": "",
        "location": "SilverLine Hospital Trichy",
        "thumbnail": "/Gallery/Events/Hospital%20Inogration/1.jpg",
        "images": [
            "/Gallery/Events/Hospital%20Inogration/1.jpg",
            "/Gallery/Events/Hospital%20Inogration/2.jpg",
            "/Gallery/Events/Hospital%20Inogration/3.jpg",
            "/Gallery/Events/Hospital%20Inogration/4.jpg",
            "/Gallery/Events/Hospital%20Inogration/5.jpg",
            "/Gallery/Events/Hospital%20Inogration/6.jpg",
            "/Gallery/Events/Hospital%20Inogration/7.jpg",
            "/Gallery/Events/Hospital%20Inogration/8.jpg",
            "/Gallery/Events/Hospital%20Inogration/9.jpg",
            "/Gallery/Events/Hospital%20Inogration/10.jpg"
        ]
    },
    {
        "id": "radiotherapy-inogration",
        "slug": "radiotherapy-inogration",
        "name": "Radiotherapy Inogration",
        "title": "Radiotherapy Inogration",
        "folder": "/Gallery/Events/Radiotherapy Inogration",
        "category": "Hospital Events",
        "date": "",
        "description": "",
        "location": "SilverLine Hospital Trichy",
        "thumbnail": "/Gallery/Events/Radiotherapy%20Inogration/1.jpeg",
        "images": [
            "/Gallery/Events/Radiotherapy%20Inogration/1.jpeg",
            "/Gallery/Events/Radiotherapy%20Inogration/2.jpeg",
            "/Gallery/Events/Radiotherapy%20Inogration/3.jpeg",
            "/Gallery/Events/Radiotherapy%20Inogration/4.jpeg",
            "/Gallery/Events/Radiotherapy%20Inogration/5.jpeg",
            "/Gallery/Events/Radiotherapy%20Inogration/6.jpeg",
            "/Gallery/Events/Radiotherapy%20Inogration/7.jpeg",
            "/Gallery/Events/Radiotherapy%20Inogration/8.jpeg"
        ]
    },
    {
        "id": "silverline-survivors-day-2026",
        "slug": "silverline-survivors-day-2026",
        "name": "Silverline Survivors Day 2026",
        "title": "Silverline Survivors Day 2026",
        "folder": "/Gallery/Events/Silverline Survivors Day 2026",
        "category": "Hospital Events",
        "date": "",
        "description": "",
        "location": "SilverLine Hospital Trichy",
        "thumbnail": "/Gallery/Events/Silverline%20Survivors%20Day%202026/DSC_0629.JPG",
        "images": [
            "/Gallery/Events/Silverline%20Survivors%20Day%202026/DSC_0629.JPG",
            "/Gallery/Events/Silverline%20Survivors%20Day%202026/DSC_0848.JPG",
            "/Gallery/Events/Silverline%20Survivors%20Day%202026/DSC_0854.JPG",
            "/Gallery/Events/Silverline%20Survivors%20Day%202026/DSC_0856.JPG",
            "/Gallery/Events/Silverline%20Survivors%20Day%202026/DSC_0863.JPG",
            "/Gallery/Events/Silverline%20Survivors%20Day%202026/DSC_0893.JPG",
            "/Gallery/Events/Silverline%20Survivors%20Day%202026/DSC_0946.JPG",
            "/Gallery/Events/Silverline%20Survivors%20Day%202026/DSC_0989.JPG",
            "/Gallery/Events/Silverline%20Survivors%20Day%202026/DSC_1024.JPG",
            "/Gallery/Events/Silverline%20Survivors%20Day%202026/DSC_1051.JPG",
            "/Gallery/Events/Silverline%20Survivors%20Day%202026/DSC_1080.JPG"
        ]
    }
];
