/**
 * Generated Insurance Partners Manifest
 * --------------------------------------
 * This file is automatically generated by scripts/generate-insurance-manifest.js
 * Scans public/Standby/Insurance/ and outputs logos in natural numeric order.
 * 
 * Do not edit this file manually. Add or remove images in public/Standby/Insurance/.
 */

export const insuranceLogos: string[] = [
  "/Standby/Insurance/1.png",
  "/Standby/Insurance/2.png",
  "/Standby/Insurance/3.png",
  "/Standby/Insurance/4.png",
  "/Standby/Insurance/5.png",
  "/Standby/Insurance/6.png",
  "/Standby/Insurance/7.png",
  "/Standby/Insurance/8.png",
  "/Standby/Insurance/9.png",
  "/Standby/Insurance/10.png",
  "/Standby/Insurance/11.png",
  "/Standby/Insurance/12.png",
  "/Standby/Insurance/13.png",
  "/Standby/Insurance/14.png"
];

export default insuranceLogos;
