import React from 'react';

export const specialtiesList = [
  {
    id: 'general-medicine',
    name: 'General Medicine',
    shortDescription: 'Primary care and management of common illnesses for the Trichy community.',
    iconPath: 'imagePaths.specialties.icons.generalMedicine',
    heroImage: 'imagePaths.specialties.generalMedicineHero',
    description: 'The first point of contact for general health issues in Trichy, providing diagnosis, treatment, and preventive care.',
    services: ['Annual Physical Exams', 'Management of Chronic Diseases', 'Preventive Health Screenings', 'Acute Illness Care'],
    gallery: [],
    keywords: ['general medicine', 'physician'],
    faqs: []
  },
  {
    id: 'orthopedics',
    name: 'Orthopedics',
    shortDescription: 'Restoring mobility for bones, joints, and muscles in Trichy.',
    iconPath: 'imagePaths.specialties.icons.orthopedics',
    heroImage: 'imagePaths.specialties.orthopedicsHero',
    description: `Our Orthopedics department in Trichy is dedicated to treating injuries and diseases of the musculoskeletal system. From sports injuries to joint replacements, our team provides comprehensive care.`,
    services: ['Joint Replacement Surgery (Hip, Knee, Shoulder)', 'Sports Medicine', 'Spine Surgery', 'Trauma and Fracture Care', 'Hand and Upper Extremity Surgery', 'Physical Therapy and Rehabilitation'],
    gallery: [],
    keywords: ['orthopedics', 'orthopaedic', 'orthoscopic', 'trauma', 'sports medicine', 'bone'],
    faqs: []
  },
  {
    id: 'ent',
    name: 'ENT',
    shortDescription: 'Comprehensive care for ear, nose, and throat disorders in Trichy.',
    iconPath: 'imagePaths.specialties.icons.ent',
    heroImage: 'imagePaths.specialties.entHero',
    description: 'Our Trichy ENT specialists provide comprehensive medical and surgical care for conditions affecting the ear, nose, throat, head, and neck.',
    services: ['Sinus Surgery', 'Tonsillectomy', 'Hearing Loss Treatment', 'Voice and Swallowing Disorders'],
    gallery: [],
    keywords: ['ent', 'ear', 'nose', 'throat'],
    faqs: []
  },
  {
    id: 'pulmonology',
    name: 'Pulmonology',
    shortDescription: 'Top treatment for respiratory and lung diseases in Trichy.',
    iconPath: 'imagePaths.specialties.icons.pulmonology',
    heroImage: 'imagePaths.specialties.pulmonologyHero',
    description: `Our Pulmonology department in Trichy focuses on the diagnosis and management of diseases of the respiratory system, including the lungs, airways, and chest wall.`,
    services: ['Asthma and COPD Management', 'Sleep Apnea Diagnosis and Treatment', 'Pulmonary Function Testing', 'Bronchoscopy', 'Interstitial Lung Disease Care', 'Critical Care Medicine'],
    gallery: [],
    keywords: ['pulmonology', 'lungs', 'respiratory'],
    faqs: []
  },
  {
    id: 'surgical-gastroenterology',
    name: 'Surgical Gastroenterology',
    shortDescription: 'Surgical solutions for digestive system diseases in Trichy.',
    iconPath: 'imagePaths.specialties.icons.surgicalGastroenterology',
    heroImage: 'imagePaths.specialties.surgicalGastroenterologyHero',
    description: 'Our expert surgeons in Trichy provide advanced surgical options for complex diseases of the gastrointestinal tract, liver, and pancreas.',
    services: ['Liver Resection', 'Pancreatic Surgery', 'Esophageal Surgery', 'Laparoscopic Colectomy'],
    gallery: [],
    keywords: ['surgical gastroenterology'],
    faqs: []
  },
  {
    id: 'cardiology',
    name: 'Cardiology',
    shortDescription: 'Expert cardiology care in Trichy for heart and vascular conditions.',
    iconPath: 'imagePaths.specialties.icons.cardiology',
    heroImage: 'imagePaths.specialties.cardiologyHero',
    description: `Our Cardiology department in Trichy provides comprehensive care for patients with heart and vascular diseases. We offer a full range of services from diagnosis to treatment and rehabilitation, utilizing state-of-the-art technology and a patient-centered approach.`,
    services: ['Echocardiogram', 'Stress Testing', 'Cardiac Catheterization', 'Coronary Angioplasty', 'Heart Rhythm Management', 'Heart Failure Clinic'],
    gallery: [],
    keywords: ['cardiology', 'cardiologist', 'heart'],
    faqs: []
  },
  {
    id: 'surgical-oncology',
    name: 'Surgical Oncology',
    shortDescription: 'Pioneering surgical removal of cancerous tumors in Trichy.',
    iconPath: 'imagePaths.specialties.icons.surgicalOncology',
    heroImage: 'imagePaths.specialties.surgicalOncologyHero',
    description: 'Our Surgical Oncology department in Trichy specializes in the surgical management of cancer, including biopsies, tumor removal, and complex cancer-related surgeries.',
    services: ['Tumor Resection', 'Mastectomy', 'Lymph Node Biopsy', 'Cytoreductive Surgery'],
    gallery: [],
    keywords: ['surgical oncology', 'surgical oncologist'],
    faqs: []
  },
  {
    id: 'critical-care',
    name: 'Critical Care',
    shortDescription: 'Intensive care for critically ill patients in Trichy.',
    iconPath: 'imagePaths.specialties.icons.criticalCare',
    heroImage: 'imagePaths.specialties.criticalCareHero',
    description: 'Providing advanced monitoring and life-sustaining treatments for patients with life-threatening conditions in our state-of-the-art ICU in Trichy.',
    services: ['24/7 ICU Monitoring', 'Ventilator Management', 'Sepsis Treatment', 'Post-operative Intensive Care'],
    gallery: [],
    keywords: ['critical care', 'icu', 'intensive care'],
    faqs: []
  },
  {
    id: 'cardiothoracic-surgery',
    name: 'Cardiothoracic Surgery',
    shortDescription: 'Advanced surgical treatment for heart and chest diseases in Trichy.',
    iconPath: 'imagePaths.specialties.icons.cardiothoracicSurgery',
    heroImage: 'imagePaths.specialties.cardiothoracicSurgeryHero',
    description: 'Specializing in surgical procedures of the heart, lungs, esophagus, and other organs in the chest, our Trichy-based team is a pioneer in the region.',
    services: ['Coronary Artery Bypass Grafting', 'Heart Valve Repair/Replacement', 'Aortic Surgery', 'Lung Cancer Surgery'],
    gallery: [],
    keywords: ['cardiothoracic', 'heart surgery'],
    faqs: []
  },
  {
    id: 'neurology',
    name: 'Neurology',
    shortDescription: 'Advanced care for brain and nervous system disorders in Trichy.',
    iconPath: 'imagePaths.specialties.icons.neurology',
    heroImage: 'imagePaths.specialties.neurologyHero',
    description: `Our Neurology department in Trichy specializes in the diagnosis and treatment of disorders affecting the brain, spinal cord, and nerves.`,
    services: ['EEG and EMG Testing', 'Stroke Care and Rehabilitation', 'Epilepsy Management', 'Movement Disorder Clinic', 'Headache and Migraine Treatment', 'Memory Disorder Evaluation'],
    gallery: [],
    keywords: ['neurology', 'neurologist', 'brain', 'stroke'],
    faqs: []
  },
  {
    id: 'nephrology',
    name: 'Nephrology',
    shortDescription: 'Expert care for kidney diseases and management in Trichy.',
    iconPath: 'imagePaths.specialties.icons.nephrology',
    heroImage: 'imagePaths.specialties.urologyHero',
    description: 'Our Nephrology department provides comprehensive care for acute and chronic kidney diseases, including dialysis and transplant evaluation.',
    services: ['Dialysis', 'CRRT', 'Peritoneal Dialysis', 'Kidney Biopsy'],
    gallery: [],
    keywords: ['nephrology', 'kidney', 'dialysis'],
    faqs: []
  },
  {
    id: 'medical-oncology',
    name: 'Medical Oncology',
    shortDescription: 'Comprehensive cancer treatment and support at Trichy\'s best hospital.',
    iconPath: 'imagePaths.specialties.icons.medicalOncology',
    heroImage: 'imagePaths.specialties.oncologyHero',
    description: `As Trichy's pioneer multi-speciality hospital, we offer a multidisciplinary approach to cancer care, bringing together experts in medical, surgical, and radiation oncology.`,
    services: ['Chemotherapy', 'Immunotherapy', 'Targeted Therapy', 'Hormone Therapy', 'Genetic Counseling'],
    gallery: [],
    keywords: ['oncology', 'cancer', 'onco pathologist'],
    faqs: []
  },
  {
    id: 'medical-gastroenterology',
    name: 'Medical Gastroenterology',
    shortDescription: 'Specialized care for digestive system health in Trichy.',
    iconPath: 'imagePaths.specialties.icons.medicalGastroenterology',
    heroImage: 'imagePaths.specialties.gastroHero',
    description: `We provide expert gastroenterology care in Trichy for a wide range of digestive diseases. Our team uses the latest diagnostic and therapeutic techniques to ensure the best possible outcomes for our patients.`,
    services: ['Endoscopy and Colonoscopy', 'Liver Disease Management', 'Inflammatory Bowel Disease (IBD) Care', 'Acid Reflux (GERD) Treatment', 'Pancreatic and Biliary Services', 'Nutritional Counseling'],
    gallery: [],
    keywords: ['gastroenterology', 'gastroenterologist', 'digestive'],
    faqs: []
  },
  {
    id: 'general-surgery',
    name: 'General Surgery',
    shortDescription: 'A wide range of common surgical procedures performed by top surgeons in Trichy.',
    iconPath: 'imagePaths.specialties.icons.generalSurgery',
    heroImage: 'imagePaths.specialties.generalSurgeryHero',
    description: 'Our surgical department in Trichy focuses on abdominal contents including esophagus, stomach, small intestine, large intestine, liver, pancreas, gallbladder, appendix and bile ducts, and often the thyroid gland.',
    services: ['Appendectomy', 'Hernia Repair', 'Gallbladder Removal', 'Colon Surgery'],
    gallery: [],
    keywords: ['general surgery', 'general surgeon', 'laparoscopic'],
    faqs: []
  },
  {
    id: 'radiation-oncology',
    name: 'Radiation Oncology',
    shortDescription: 'Targeted radiation therapy for cancer treatment in Trichy.',
    iconPath: 'imagePaths.specialties.icons.radiationOncology',
    heroImage: 'imagePaths.specialties.radiationOncologyHero',
    description: 'Using high-energy radiation to shrink tumors and kill cancer cells as part of a comprehensive cancer treatment plan at our advanced facility in Trichy.',
    services: ['IMRT', 'IGRT', 'Stereotactic Radiosurgery (SRS)', 'Brachytherapy'],
    gallery: [],
    keywords: ['radiation oncology', 'radiation'],
    faqs: []
  },
  {
    id: 'neuro-surgery',
    name: 'Neuro Surgery',
    shortDescription: 'Advanced surgical treatment for complex neurological conditions.',
    iconPath: 'imagePaths.specialties.icons.neuroSurgery',
    heroImage: 'imagePaths.specialties.neurologyHero',
    description: 'Expert surgical care for the brain, spinal cord, and nervous system, treating tumors, trauma, and degenerative conditions.',
    services: ['Brain Tumor Resection', 'Spine Surgery', 'Microdiscectomy', 'Neuro-trauma Care'],
    gallery: [],
    keywords: ['neuro surgery', 'neurosurgeon', 'brain surgery'],
    faqs: []
  },
  {
    id: 'transplant-surgery',
    name: 'Transplant Surgery',
    shortDescription: 'Pioneering organ transplant procedures and follow-up care.',
    iconPath: 'imagePaths.specialties.icons.transplantSurgery',
    heroImage: 'imagePaths.specialties.generalSurgeryHero',
    description: 'Our transplant team specializes in multi-organ transplantation, providing life-saving procedures with comprehensive pre- and post-transplant support.',
    services: ['Kidney Transplant', 'Liver Transplant', 'Post-Transplant Care', 'Donor Evaluation'],
    gallery: [],
    keywords: ['transplant', 'kidney transplant', 'liver transplant'],
    faqs: []
  },
  {
    id: 'bone-marrow-transplant',
    name: 'Bone Marrow Transplant',
    shortDescription: 'Advanced cellular therapy for hematological conditions.',
    iconPath: 'imagePaths.specialties.icons.boneMarrowTransplant',
    heroImage: 'imagePaths.specialties.generalMedicineHero',
    description: 'Expert bone marrow and stem cell transplantation for various blood disorders and cancers.',
    services: ['Autologous BMT', 'Allogeneic BMT', 'Stem Cell Harvest', 'Post-BMT Monitoring'],
    gallery: [],
    keywords: ['bmt', 'bone marrow', 'stem cell'],
    faqs: []
  },
  {
    id: 'vascular-surgery',
    name: 'Vascular Surgery',
    shortDescription: 'Expert surgical management of vascular and vein conditions.',
    iconPath: 'imagePaths.specialties.icons.vascularSurgery',
    heroImage: 'imagePaths.specialties.cardiologyHero',
    description: 'Comprehensive treatment for diseases of the vascular system, including arteries, veins, and lymphatic circulation.',
    services: ['Angioplasty', 'Varicose Vein Treatment', 'Aneurysm Repair', 'Bypass Surgery'],
    gallery: [],
    keywords: ['vascular', 'vein', 'artery'],
    faqs: []
  },
  {
    id: 'gynaecology',
    name: 'Gynaecology',
    shortDescription: 'Comprehensive care for women’s health at every stage of life.',
    iconPath: 'imagePaths.specialties.icons.gynaecology',
    heroImage: 'imagePaths.specialties.gynaecologyHero',
    description: 'Our Gynaecology department in Trichy offers expert care for women, from routine screenings to advanced surgical procedures, ensuring health and wellness.',
    services: ['Antenatal Care', 'Gynaecological Surgery', 'Menopause Management', 'Infertility Treatment'],
    gallery: [],
    keywords: ['gynaecology', 'obstetrics', 'womens health'],
    faqs: []
  },
  {
    id: 'robotic-surgery',
    name: 'Robotic Surgery',
    shortDescription: 'Precision minimally invasive surgery assisted by advanced technology.',
    iconPath: 'imagePaths.specialties.icons.roboticSurgery',
    heroImage: 'imagePaths.specialties.generalMedicineHero',
    description: 'Utilizing state-of-the-art robotic systems to perform complex procedures with greater precision, smaller incisions, and faster recovery.',
    services: ['Robotic Urology', 'Robotic Gynecology', 'Robotic General Surgery', 'Precision Resection'],
    gallery: [],
    keywords: ['robotic', 'minimally invasive', 'precision surgery'],
    faqs: []
  },
  {
    id: 'pain-palliative-care',
    name: 'Pain & Palliative Care',
    shortDescription: 'Compassionate care focused on improving quality of life.',
    iconPath: 'imagePaths.specialties.icons.painPalliativeCare',
    heroImage: 'imagePaths.specialties.generalMedicineHero',
    description: 'Specialized medical care for people living with serious illnesses, focused on providing relief from symptoms and stress.',
    services: ['Chronic Pain Management', 'Symptom Control', 'End-of-life Care', 'Psychological Support'],
    gallery: [],
    keywords: ['pain management', 'palliative care', 'quality of life'],
    faqs: []
  },
  {
    id: 'urology',
    name: 'Urology',
    shortDescription: 'Comprehensive care for urinary tract and male reproductive health.',
    iconPath: 'imagePaths.specialties.icons.urology',
    heroImage: 'imagePaths.specialties.urologyHero',
    description: 'Our Urology department provides advanced treatment for kidney stones, prostate health, and urinary tract disorders.',
    services: ['Kidney Stone Removal', 'Prostate Surgery', 'Uro-Oncology', 'Pediatric Urology'],
    gallery: [],
    keywords: ['urology', 'urologist', 'kidney stone'],
    faqs: []
  },
];